global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9876
rule_files:

scrape_configs:
  - job_name: "LINUX"
    relabel_configs:
      - source_labels: ["job"]
        target_label: "task"
      - source_labels: ["instanceName"]
        target_label: "job"
    static_configs:
      - targets: ["localhost:9100"]
        labels:
          "instanceName": "Linux OS Test"
  - job_name: "WAS"
    relabel_configs:
      - source_labels: ["job"]
        target_label: "task"
      - source_labels: ["instanceName"]
        target_label: "job"
    static_configs:
      - targets: ["localhost:8000"]
        labels:
          "instanceName": "WAS Server1"
          "__metrics_path__": "/actuator/prometheus"
