name: FE CI

on:
  push:
    branches: [ dev, dev_frontend ]
  pull_request:
    branches: [ dev, dev_frontend ]

defaults:
  run:
    shell: bash
    working-directory: ../Frontend

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ESLint
        run: |
          npm install eslint@8.14.0
          npm install @microsoft/eslint-formatter-sarif@2.1.7

      - name: Run ESLint
        run: npx eslint .
          --config .eslintrc.js
          --ext .ts,.tsx
  build:
    needs: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install # will run `yarn install` command
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: build # will run `yarn build` command
  
  deploy:
    needs: [eslint, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './dist'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
